version: "3"
services:
  piecewise:
    image: test:latest
    container_name: ${PIECEWISE_CONTAINER_NAME}
    depends_on:
      - piecewise-db
    networks:
      - piecewise-private
      - piecewise-public
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PIECEWISE_LOG_LEVEL: ${PIECEWISE_LOG_LEVEL:-debug}
      PIECEWISE_HOST: ${PIECEWISE_HOST:-0.0.0.0}
      PIECEWISE_PORT: ${PIECEWISE_PORT:-3000}
      PIECEWISE_DB_HOST: ${PIECEWISE_DB_USER:-piecewise-db}
      PIECEWISE_DB_USER: ${PIECEWISE_DB_USER:-piecewise}
      PIECEWISE_DB_PASSWORD: ${PIECEWISE_DB_PASSWORD:-piecewise}
      PIECEWISE_DB_DATABASE: ${PIECEWISE_DB_DATABASE:-piecewise}

  piecewise-db:
    container_name: ${PIECEWISE_DB_CONTAINER_NAME}
    image: postgres:12-alpine
    volumes:
      - piecewise-db_data:/var/lib/postgresql/data
    networks:
      - piecewise-private
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${PIECEWISE_DB_USER:-piecewise}
      POSTGRES_PASSWORD: ${PIECEWISE_DB_PASSWORD:-piecewise}
      POSTGRES_DB: ${PIECEWISE_DB_DATABASE:-piecewise}

volumes:
  piecewise-db_data: {}

networks:
  piecewise-private:
    internal: true
  piecewise-public:
